# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Amirza_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 321)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Pirate Icon 21.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.978)
        MainWindow.setStyleSheet("color:#FCE400;background-color:#3C3F41;")
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 541, 31))
        self.lineEdit.setStyleSheet("background-color:#F5F5F5 ; color:black")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -6, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("overflow : auto;")
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 83, 71, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setWhatsThis("")
        self.pushButton.setStyleSheet("background-color :#B8860B; color: black")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 150, 540, 131))
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser.setStyleSheet("color:white ; align:\"center\";font-size:14px;")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser.setObjectName("textBrowser")
        self.label_Error = QtWidgets.QLabel(self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(147, 62, 271, 16))
        self.label_Error.setStyleSheet("color:red;")
        self.label_Error.setText("")
        self.label_Error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Error.setObjectName("label_Error")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(17, 120, 535, 23))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(284, 83, 71, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setWhatsThis("")
        self.pushButton_2.setStyleSheet("background-color :#B8860B; color: black")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox3.setGeometry(QtCore.QRect(11, 64, 59, 15))
        self.checkBox3.setChecked(True)
        self.checkBox3.setObjectName("checkBox3")
        self.checkBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox4.setGeometry(QtCore.QRect(11, 77, 59, 15))
        self.checkBox4.setChecked(True)
        self.checkBox4.setObjectName("checkBox4")
        self.checkBoxMore = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxMore.setGeometry(QtCore.QRect(11, 90, 59, 15))
        self.checkBoxMore.setChecked(True)
        self.checkBoxMore.setObjectName("checkBoxMore")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 20))
        self.menubar.setObjectName("menubar")
        self.menuFlie = QtWidgets.QMenu(self.menubar)
        self.menuFlie.setObjectName("menuFlie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setShortcutVisibleInContextMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.menuFlie.addAction(self.actionExit)
        self.menubar.addAction(self.menuFlie.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.checkBox3)
        MainWindow.setTabOrder(self.checkBox3, self.checkBox4)
        MainWindow.setTabOrder(self.checkBox4, self.checkBoxMore)
        MainWindow.setTabOrder(self.checkBoxMore, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.textBrowser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Amirza Hacker"))
        self.lineEdit.setStatusTip(_translate("MainWindow", "You can type here"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your seperated characters here..."))
        self.label.setText(_translate("MainWindow", "Amirza Hacker:"))
        self.pushButton.setToolTip(_translate("MainWindow", "Shortcut : Enter"))
        self.pushButton.setStatusTip(_translate("MainWindow", "Click to go"))
        self.pushButton.setText(_translate("MainWindow", "Go"))
        self.textBrowser.setStatusTip(_translate("MainWindow", "Results"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px;\"><br /></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Shortcut : CTRL + C"))
        self.pushButton_2.setStatusTip(_translate("MainWindow", "Click to cancel"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.checkBox3.setText(_translate("MainWindow", "3 letters"))
        self.checkBox4.setText(_translate("MainWindow", "4 letters"))
        self.checkBoxMore.setText(_translate("MainWindow", "5 or more"))
        self.menuFlie.setTitle(_translate("MainWindow", "Menu"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
